### ISSUE TITLE
Add AWS credentials to .travis.yml

### ISSUE THREAD

**Issue by chuwy** [snowplow/event-manifest-cleaner#1]
Hey @alexanderdean,

Can we please add AWS creds:

* `AWS_ACCESS_KEY`
* `AWS_SECRET_KEY`

Also we need to enable Travis CI for this project and confirm please that we're publishing only to `s3://snowplow-hosted-assets/4-storage/event-manifest-cleaner/`?

**Comment by alexanderdean** [comment]
`s3://snowplow-hosted-assets/4-storage/event-manifest-cleaner/` looks good to me.

**Comment by alexanderdean** [comment]
Enabled Travis
